server:
  port: 8080

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: notif_user
    password: notif_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rabit_gust
    password: rabit_gust_6006

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace